name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Trigger per change
        run: |
           git diff --name-only HEAD HEAD^1 | grep '^test/*.ini$' | while read -r line; do gh workflow run "multiple-run" --ref main ;done


