name: "multiple run" 
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."